version: '2'
services:
  web:
    build: .docker/nginx/
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/vhosts/frontend.i-mscp.net
    networks:
      - bridged-network
  php-fpm:
    image: php:7.1-fpm
    build: .docker/php/
    volumes:
      - .:/var/vhosts/frontend.i-mscp.net
    networks:
      - bridged-network
networks:
    bridged-network:
      driver: bridge
